name: Terraform PR preview
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/*terragrunt.yml'
jobs:
  preview:
    name: Preview ${{ matrix.project }}-${{ github.base_ref }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        project: [global, monitoring] # done in order, global must come first  # left off here
    steps:
      - uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration
          job-status: ${{ job.status }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '15.11.0'
      - run: npm install --global cdktf-cli@next
      - name: chefdk ${{ matrix.project }}-${{ github.base_ref }}
        working_directory: ${{ matrix.project }}
        run: |
          pwd
          echo working on ${{ matrix.project }}-${{ github.base_ref }}
          cdktf --version
          cdktf diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          S3_BACKEND_URL: s3://fr-personal-account-config/cdktf-test/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: 1
