name: Terraform update environment
on:
  push:
    branches:
      - production
      - staging
    paths:
      - 'global/**'
      - 'monitoring/**'
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        project: [ global, monitoring ] # done in order, global must come first
    steps:
      - uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration
          job-status: ${{ job.status }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '15.11.0'
      - run: npm install --global cdktf-cli@next
      - name: Get branch name
        id: branch_finder
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Check output
        run: echo ${{ steps.branch_finder.outputs.short_ref }}
      - name: cdktf ${{ matrix.project }}-${{ steps.branch_finder.outputs.short_ref }}
        working_directory: ${{ matrix.project }}
        run: |
          cdktf get
          echo cdktf deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          S3_BACKEND_URL: s3://fr-personal-account-config/cdktf-test/
          STACK_NAME: ${{ matrix.project }}-${{ steps.branch_finder.outputs.short_ref }}